state_list = [{'state_name':'Alabama', 'state_abrev':'AL'},
                  {'state_name':'Alaska', 'state_abrev': 'AK'},
                  {'state_name':'Arizona', 'state_abrev': 'AZ'},
                  {'state_name':'Arkansas', 'state_abrev': 'AR'},
                  {'state_name':'California', 'state_abrev':'CA'},
                  {'state_name':'Colorado', 'state_abrev': 'CO'},
                  {'state_name':'Connecticut', 'state_abrev': 'CT'},
                  {'state_name':'Delaware', 'state_abrev':'DE'},
                  {'state_name':'District of Columbia', 'state_abrev':'DC'},
                  {'state_name':'Florida', 'state_abrev': 'FL'},
                  {'state_name':'Georgia', 'state_abrev':'GA'},
                  {'state_name':'Hawaii', 'state_abrev':'HI'},
                  {'state_name':'Idaho', 'state_abrev':'ID'},
                  {'state_name':'Illinois', 'state_abrev':'IL'},
                  {'state_name':'Indiana', 'state_abrev':'IN'},
                  {'state_name': 'Iowa', 'state_abrev': 'IA'},
                  {'state_name': 'Kansas', 'state_abrev': 'KS'},
                  {'state_name': 'Kentucky', 'state_abrev': 'KY'},
                  {'state_name': 'Louisiana', 'state_abrev': 'LA'},
                  {'state_name': 'Maine', 'state_abrev': 'ME'},
                  {'state_name': 'Maryland', 'state_abrev': 'MD'},
                  {'state_name': 'Massachusetts', 'state_abrev': 'MA'},
                  {'state_name': 'Michigan', 'state_abrev': 'MI'},
                  {'state_name': 'Minnesota', 'state_abrev': 'MN'},
                  {'state_name': 'Mississippi', 'state_abrev': 'MS'},
                  {'state_name': 'Missouri', 'state_abrev': 'MS'},
                  {'state_name': 'Montana', 'state_abrev': 'MT'},
                  {'state_name': 'Nebraska', 'state_abrev': 'NE'},
                  {'state_name': 'Nevada', 'state_abrev': 'NV'},
                  {'state_name': 'New Hampshire', 'state_abrev': 'NH'},
                  {'state_name': 'New Jersey', 'state_abrev': 'NJ'},
                  {'state_name': 'New Mexico', 'state_abrev': 'NM'},
                  {'state_name': 'New York', 'state_abrev': 'NY'},
                  {'state_name': 'North Carolina', 'state_abrev': 'NC'},
                  {'state_name': 'North Dakota', 'state_abrev': 'ND'},
                  {'state_name': 'Ohio', 'state_abrev': 'OH'},
                  {'state_name': 'Oklahoma', 'state_abrev': 'OK'},
                  {'state_name': 'Oregon', 'state_abrev': 'OR'},
                  {'state_name': 'Pennsylvania', 'state_abrev': 'PA'},
                  {'state_name': 'Rhode Island', 'state_abrev': 'RI'},
                  {'state_name': 'South Carolina', 'state_abrev': 'SC'},
                  {'state_name': 'South Dakota', 'state_abrev': 'SD'},
                  {'state_name': 'Tennessee', 'state_abrev': 'TN'},
                  {'state_name': 'Texas', 'state_abrev': 'TX'},
                  {'state_name': 'Utah', 'state_abrev': 'UT'},
                  {'state_name': 'Vermont', 'state_abrev': 'VT'},
                  {'state_name': 'Virginia', 'state_abrev': 'VI'},
                  {'state_name': 'Washington', 'state_abrev': 'WA'},
                  {'state_name': 'West Virginia', 'state_abrev': 'WV'},
                  {'state_name': 'Wisconsin', 'state_abrev': 'WI'},
                  {'state_name': 'Wyoming', 'state_abrev': 'WY'},
                  {'state_name': 'Guam', 'state_abrev': 'GU'},
                  {'state_name': 'Puerto Rico', 'state_abrev': 'PR'},
                  {'state_name': 'Virgin Islands', 'state_abrev': 'VG'}]